version: '2'

networks:
  app-tier:
    driver: bridge

services:
 cas1:
    container_name: cas1
    image: "cassandra:3.10"
    volumes:
      - /home/sroziewski/docker/cassandra/seed/cluster/data:/var/lib/cassandra/data
      - /home/sroziewski/docker/cassandra/conf:/tmp/conf
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_DC=datacenter1
      - JVM_EXTRA_OPTS=-Dcassandra.config=/tmp/conf/seed.yaml
    networks:
      - app-tier
 cas2:
  container_name: cas2
  image: "cassandra:3.10"
  volumes:
      - /home/sroziewski/docker/cassandra/node/cluster/data:/var/lib/cassandra/data
      - /home/sroziewski/docker/cassandra/conf:/tmp/conf
  ports:
      - 9043:9042
  command: bash -c 'sleep 60;  /docker-entrypoint.sh cassandra -f'
  depends_on:
    - cas1
  environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_SEEDS=cas1
      - JVM_EXTRA_OPTS=-Dcassandra.config=/tmp/conf/node.yaml
  networks:
      - app-tier
